# Generated by Django 4.1.7 on 2023-03-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_labeltotask_task_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeltotask',
            old_name='tasks',
            new_name='task',
        ),
    ]
